### ISSUE TITLE
reasoner issues

### ISSUE THREAD

**Issue by tgbugs** [SciGraph/SciGraph#150]
When the UBERON partonomy is ingested into scigraph the reasoner appears to make some rather.... amusing inferences: http://kaa.neuinfo.org:9000/scigraph/graph/neighbors/UBERON_0002129?relationshipType=BFO_0000050&direction=INCOMING&depth=1
For example asserting that the 'upper urinary tract' is 'part_of' 'cerebellar cortex.'
This makes it quite hard to use the uberon partonomy from scigraph.
I have only loaded uberon.owl on that instance of scigraph.

@cmungall is this a known issue?

**Comment by tgbugs** [comment]
The relevant lines from the graphload yaml are:

    ontologies:
      - url: http://purl.obolibrary.org/obo/uberon.owl
        reasonerConfiguration:
          factory: org.semanticweb.elk.owlapi.ElkReasonerFactory

**Comment by cmungall** [comment]
No, this is not a known issue. I can confirm that the mistake isn't in uberon, as you have determined yourself via DL queries. See also http://purl.obolibrary.org/obo/UBERON_0011143 - no link to the brain to be found! It would be hard for a link like this to get into uberon, as there are strict spatial disjointness axioms that must be satisfied in order to build a release.

One hypothesis is as follows: there is some axiom in the complete ontology set that is causing a global inconsistency. When this happens an OWL reasoner can give odd results. However, this should not be the case as @ccondit built in failfast checks so that loading would fail if the reasoner detected incoherency. It strikes me I may have underspecified this: the failfast condition should be that *any* incoherency is found, where there are two types of incoherency: (1) there exists at least one class that is unsatisfiable or (2) the ontology as a whole is inconsistent.

But this is unlikely to be the cause, because it looks like you have only the single ontology in your load chain, and it's impossible for uberon to be incoherent (in the owl sense), without some external ontology coming along and mushing axioms.

So it's pointing at some kind of load error. This is weird as I'm sure we would have noticed something like this by now.

Another possibility is that it's something to do with GCIs. I will try and explore this more later, but if you would like some other avenues to test until I get to this, you could try loading uberon-basic. 

http://purl.obolibrary.org/obo/uberon/basic.obo

(the OWLAPI should load the obo transparently, @hdietze can confirm)

**Comment by cmungall** [comment]
Another avenue to explore would be to see how the underlying Neo4J graph looks. It may be something in the services layer rather than the graph (but this seems unlikely).

There are different ways to explore the graph, I like the neo4j shell: https://github.com/SciGraph/SciGraph/wiki/Using-SciGraph-with-neo4j-shell

**Comment by cmungall** [comment]
I spoke too soon, will you look at that, urinary tracts in the brain in monarch:

http://datagraph.monarchinitiative.org/graph/neighbors/UBERON_0002129?relationshipType=BFO_0000050&direction=INCOMING&depth=1

that's the sacrificial public server that may be out of date.

The cortex is totally fine in our more recent dev and stage instances:

http://geoffrey.crbs.ucsd.edu:9000/scigraph/graph/neighbors/UBERON_0002129?relationshipType=BFO_0000050&direction=INCOMING&depth=1

http://alice.crbs.ucsd.edu:9000/scigraph/graph/neighbors/UBERON_0002129?relationshipType=BFO_0000050&direction=INCOMING&depth=1

I also just tried a load of just uberon on localhost, and could not replicate the problem

So it seems like something that was a problem and has since been fixed. That may have been a problem in uberon (I think this unlikely for the reasons mentioned above) or maybe you're using a much older scigraph...?

Can you confirm when you did the load, and what build of SG you're using? If you retry does the problem go away?

**Comment by ccondit** [comment]
As an aside if you just specify the reasoner class I don't think anything will be added to the ontology. You can always inspect the logs for:

````
Applying reasoned axioms: 0
````

to find out how many axioms actually were added.

**Comment by tgbugs** [comment]
Builds and loads were done today. I rebuilt on the latest scigraph from git (590394d0b1c00072030139df8dfaaeb374903f72) for both matrix and kaa. Both are loading uberon.owl directly from http://purl.obolibrary.org/obo/uberon.owl (matrix via an import in a new version of nif.owl).

**Comment by tgbugs** [comment]
http://purl.obolibrary.org/obo/uberon/basic.obo loads fine and the problem does not appear: http://kaa.neuinfo.org:3000/scigraph/graph/neighbors/UBERON_0002129?relationshipType=BFO_0000050&direction=INCOMING&depth=1.

This was loaded using the same build of scigraph with the same config files, changing only what ontology file was loaded.

**Comment by ccondit** [comment]
This was caused by a hash collision. Has been fixed for now.
