### ISSUE TITLE
add a /scigraph/vocabulary/curies service

### ISSUE THREAD

**Issue by tgbugs** [SciGraph/SciGraph#159]
There is currently a service that shows all the available prefixes at /scigraph/vocabulary/prefixes but it would also be nice to have a service that would return the curies defined for a currently running scigraph instance so you don't have to hunt down the config file (which sometimes might not be accessible). The service path should probably be /scigraph/vocabulary/curies. A nice return format would be: ```{'PREFIX1':'iripattern1', 'PREFIX2':'iripattern2'}```.

**Comment by jmcmurry** [comment]
+1 @kshefchek and I were talking about this back in November. This is related to other requests we have gotten (eg. from OMIM) so that they can link out to us. That was a one-off effort, but I would like to take this a step further and not just provide a scigraph service, but also a corresponding application page eg. http://monarchinitiative.org/OMIM which would contain a list of the IDs, each hyperlinked to its corresponding application page eg: http://monarchinitiative.org/OMIM:nnnnn.

**Comment by atorr** [comment]
I can go ahead and work on this.

**Comment by jnguyenx** [comment]
I'll take care of that since I want to check some other things related to curies, but thanks!

**Comment by atorr** [comment]
Okay

**Comment by atorr** [comment]
Hey.  Since I had already started on the issue I went ahead and pushed some code for it.  Let me know if it helps.

**Comment by jnguyenx** [comment]
Thanks I'll have a look!

**Comment by jnguyenx** [comment]
@atorr I did a similar implementation but I've put the endpoint in a different service than the vocabulary one. I've added it in the /cypher one, as curie can be used in most of the services.
