### ISSUE TITLE
Migrate to Neo4j 3.x.x

### ISSUE THREAD

**Issue by jnguyenx** [SciGraph/SciGraph#179]

**Comment by josecv** [comment]
We're looking at integrating SciGraph into [phenotips](https://github.com/phenotips/phenotips) but we depend on Lucene 5, whereas SciGraph (and Neo4j 2) depend on Lucene 3.3.

Since migrating SciGraph to Lucene 5 would probably first depend on migrating it to Neo4j 3 we're wondering what the outlook is for this particular issue, how complex is it and would we be able to help out?

**Comment by jnguyenx** [comment]
I haven't looked into it in details yet, but the major issue will be to
adapt to the new APIs. Some calls were deprecated in 2.3.x already (that's
why we were sticking with 2.2.x).

In any case this is a fairly high priority for us. I'll create a branch
soon and we'll have more visibility on the todos.

**Comment by jnguyenx** [comment]
Pending on https://github.com/neo4j/neo4j/issues/7204

**Comment by jnguyenx** [comment]
@josecv sorry it's taking so long, I'm still stuck with the issue of multiple LogEntry versions. Still waiting for the Neo4j team to come back to me.

With that said, there were some graph loads which randomly succeeded, so you might want to give a try with this branch and see what happens for you.

**Comment by jnguyenx** [comment]
Migrated to Neo4j 3.0.7 (Nov 02, 2016).
